"""Table schema definitions and generation order for synthetic data."""

from __future__ import annotations

# The order in which tables must be generated to satisfy foreign key dependencies.
GENERATION_ORDER = [
    "dim_time",
    "dim_institution",
    "dim_address",
    "dim_customer",
    "dim_merchant",
    "dim_account",
    "bridge_customer_address",
    "dim_counterparty",
    "dim_customer_scd2",
    "fact_transaction",
    "fact_payment",
    "fact_refund",
    "fact_dispute",
    "event_login",
    "event_device",
    "event_account_status_change",
    "event_rule_decision",
    "event_account_balance_daily",
]

# Explicit dependencies for each table.
DEPENDENCIES = {
    "dim_time": [],
    "dim_institution": [],
    "dim_address": [],
    "dim_customer": ["dim_address"],
    "dim_merchant": ["dim_address"],
    "dim_account": ["dim_customer", "dim_institution"],
    "bridge_customer_address": ["dim_customer", "dim_address"],
    "dim_counterparty": ["dim_merchant"],
    "dim_customer_scd2": ["dim_customer"],
    "fact_transaction": [
        "dim_time",
        "dim_customer",
        "dim_account",
        "dim_merchant",
        "dim_counterparty",
        "dim_institution",
    ],
    "fact_payment": ["fact_transaction"],
    "fact_refund": ["fact_transaction"],
    "fact_dispute": ["fact_transaction"],
    "event_login": ["dim_customer", "dim_account", "dim_time"],
    "event_device": ["dim_customer", "fact_transaction"],
    "event_account_status_change": [
        "dim_account",
        "dim_customer",
        "fact_dispute",
        "fact_transaction",
        "dim_time",
    ],
    "event_rule_decision": ["fact_transaction", "event_login", "dim_account"],
    "event_account_balance_daily": ["dim_account", "dim_time", "fact_transaction"],
}

# Expected columns for each table to enable immediate validation after generation.
EXPECTED_COLUMNS = {
    "dim_time": [
        "date_key",
        "full_date",
        "day_of_week",
        "day_name",
        "day_of_month",
        "day_of_year",
        "week_of_year",
        "month",
        "month_name",
        "quarter",
        "year",
        "is_weekend",
        "is_holiday",
        "is_month_start",
        "is_month_end",
        "is_quarter_start",
        "is_quarter_end",
        "seasonality_factor",
    ],
    "dim_institution": [
        "institution_id",
        "institution_name",
        "institution_type",
        "country_code",
        "is_active",
        "routing_number",
        "swift_code",
    ],
    "dim_address": [
        "address_id",
        "address_line1",
        "address_line2",
        "city",
        "state_code",
        "state_name",
        "postal_code",
        "country_code",
        "latitude",
        "longitude",
        "address_type",
    ],
    "dim_customer": [
        "customer_id",
        "first_name",
        "last_name",
        "email",
        "phone",
        "date_of_birth",
        "customer_since",
        "risk_tier",
        "customer_segment",
        "is_active",
        "activity_score",
        "primary_address_id",
    ],
    "dim_merchant": [
        "merchant_id",
        "merchant_name",
        "mcc_code",
        "mcc_description",
        "address_id",
        "acquirer_id",
        "risk_tier",
        "is_active",
        "popularity_score",
        "avg_transaction_amount",
        "established_date",
    ],
    "dim_account": [
        "account_id",
        "customer_id",
        "institution_id",
        "account_type",
        "account_number",
        "account_status",
        "currency",
        "opened_date",
        "closed_date",
        "credit_limit",
        "risk_tier",
    ],
    "bridge_customer_address": [
        "bridge_id",
        "customer_id",
        "address_id",
        "address_type",
        "is_current",
        "effective_from",
        "effective_to",
    ],
    "dim_counterparty": [
        "counterparty_id",
        "counterparty_type",
        "counterparty_name",
        "merchant_id",
        "external_id",
        "risk_tier",
        "is_verified",
        "country_code",
    ],
    "dim_customer_scd2": [
        "scd_id",
        "customer_id",
        "first_name",
        "last_name",
        "email",
        "risk_tier",
        "customer_segment",
        "is_active",
        "effective_from",
        "effective_to",
        "is_current",
        "version_number",
    ],
    "fact_transaction": [
        "transaction_id",
        "account_id",
        "customer_id",
        "merchant_id",
        "counterparty_id",
        "institution_id",
        "time_id",
        "transaction_ts",
        "gross_amount",
        "fee_amount",
        "net_amount",
        "currency",
        "channel",
        "status",
        "risk_tier",
        "device_id",
        "is_emulator",
        "is_fraud_flagged",
    ],
    "fact_payment": [
        "payment_id",
        "transaction_id",
        "payment_method",
        "card_network",
        "card_last_four",
        "auth_code",
        "settlement_status",
        "settlement_ts",
        "ach_return_code",
        "ach_return_reason",
        "processing_fee",
        "interchange_fee",
    ],
    "fact_refund": [
        "refund_id",
        "transaction_id",
        "refund_amount",
        "refund_reason",
        "refund_status",
        "refund_requested_ts",
        "refund_processed_ts",
        "is_partial",
        "refund_method",
        "processing_fee_refunded",
    ],
    "fact_dispute": [
        "dispute_id",
        "transaction_id",
        "dispute_reason",
        "dispute_status",
        "dispute_amount",
        "dispute_opened_ts",
        "dispute_resolved_ts",
        "resolution_outcome",
        "is_chargeback",
        "merchant_responded",
        "evidence_submitted",
        "days_to_resolution",
    ],
    "event_login": [
        "login_id",
        "customer_id",
        "account_id",
        "device_id",
        "login_ts",
        "login_outcome",
        "login_channel",
        "ip_address",
        "location_country",
        "location_city",
        "session_duration_seconds",
        "mfa_method",
    ],
    "event_device": [
        "device_id",
        "customer_id",
        "device_type",
        "device_manufacturer",
        "device_model",
        "os_version",
        "app_version",
        "is_emulator",
        "is_rooted",
        "first_seen_ts",
        "last_seen_ts",
        "risk_score",
    ],
    "event_account_status_change": [
        "event_id",
        "account_id",
        "customer_id",
        "previous_status",
        "new_status",
        "change_ts",
        "change_reason",
        "initiated_by",
        "related_dispute_id",
        "related_transaction_id",
        "notes",
    ],
    "event_rule_decision": [
        "decision_id",
        "event_type",
        "event_id",
        "account_id",
        "customer_id",
        "decision_ts",
        "decision_outcome",
        "rules_triggered",
        "rule_scores",
        "model_score",
        "decision_reason",
        "review_queue",
        "review_completed",
        "final_outcome",
    ],
    "event_account_balance_daily": [
        "balance_id",
        "account_id",
        "balance_date",
        "opening_balance",
        "closing_balance",
        "daily_credits",
        "daily_debits",
        "daily_net_change",
        "transaction_count",
        "available_credit",
        "pending_amount",
    ],
}
