"""Tests for semantic caching via Registry."""

from unittest.mock import AsyncMock, patch

import pytest
from mcp_server.services.cache_service import (
    SIMILARITY_THRESHOLD,
    get_cache_stats,
    lookup_cache,
    update_cache,
)


class TestLookupCache:
    """Unit tests for lookup_cache function."""

    @pytest.mark.asyncio
    async def test_lookup_cache_miss(self):
        """Test that cache returns None when no match found."""
        with patch(
            "mcp_server.services.cache_service.RegistryService.lookup_canonical",
            new_callable=AsyncMock,
            return_value=None,
        ):
            with patch(
                "mcp_server.services.cache_service.RegistryService.lookup_semantic",
                new_callable=AsyncMock,
                return_value=[],
            ):
                cached = await lookup_cache("What is the total revenue?", tenant_id=1)
                assert cached is None

    @pytest.mark.asyncio
    async def test_lookup_cache_signature_hit(self):
        """Test that cache returns cached SQL on exact signature match."""
        from unittest.mock import MagicMock

        mock_pair = MagicMock()
        mock_pair.signature_key = "abc123"
        mock_pair.sql_query = "SELECT SUM(amount) FROM payment;"
        mock_pair.roles = ["cache"]
        mock_pair.status = "autogenerated"

        with patch(
            "mcp_server.services.cache_service.RegistryService.lookup_canonical",
            new_callable=AsyncMock,
            return_value=mock_pair,
        ):
            cached = await lookup_cache("What is the total revenue?", tenant_id=1)

            assert cached is not None
            assert cached.value == "SELECT SUM(amount) FROM payment;"
            assert cached.similarity == 1.0
            assert cached.metadata["match_type"] == "signature"


class TestUpdateCache:
    """Unit tests for update_cache function."""

    @pytest.mark.asyncio
    async def test_update_cache(self):
        """Verify cache insertion delegates to RegistryService."""
        with patch(
            "mcp_server.services.cache_service.RegistryService.register_pair",
            new_callable=AsyncMock,
        ) as mock_register:
            await update_cache(
                "What is the total revenue?",
                "SELECT SUM(amount) FROM payment;",
                tenant_id=1,
            )

            mock_register.assert_called_once_with(
                question="What is the total revenue?",
                sql_query="SELECT SUM(amount) FROM payment;",
                tenant_id=1,
                roles=["cache"],
                status="autogenerated",
            )


class TestGetCacheStats:
    """Unit tests for get_cache_stats function."""

    @pytest.mark.asyncio
    async def test_get_cache_stats_stub(self):
        """Verify statistics stub returns pending message."""
        stats = await get_cache_stats()
        assert "status" in stats


class TestCacheConstants:
    """Test cache configuration constants."""

    def test_similarity_threshold(self):
        """Verify similarity threshold is set correctly."""
        assert SIMILARITY_THRESHOLD == 0.90
        assert 0.0 <= SIMILARITY_THRESHOLD <= 1.0
