from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class QueryPair(BaseModel):
    """Canonical representation of an NLQ-SQL pair in the unified registry.

    Attributes:
        signature_key: SHA256 hash of the SpaCy canonical fingerprint.
        tenant_id: Tenant identifier.
        fingerprint: Canonical string fingerprint.
        question: Original natural language question.
        sql_query: Corresponding SQL query.
        embedding: Vector embedding of the question.
        roles: List of usage roles (cache, example, golden).
        status: Verification status (verified, autogenerated, tombstoned).
        metadata: Custom metadata.
        performance: Execution performance metrics.
    """

    signature_key: str
    tenant_id: int
    fingerprint: str
    question: str
    sql_query: str
    embedding: Optional[List[float]] = None
    roles: List[str] = Field(default_factory=list)
    status: str = "unverified"
    metadata: Dict[str, Any] = Field(default_factory=dict)
    performance: Dict[str, Any] = Field(default_factory=dict)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = {"frozen": False}
