-- Unified NLQ-SQL Registry
-- Consolidates sql_examples, semantic_cache, and golden_dataset

CREATE TABLE IF NOT EXISTS public.query_pairs (
    signature_key VARCHAR(64) NOT NULL,
    tenant_id INT NOT NULL DEFAULT 1,
    fingerprint TEXT NOT NULL,
    question TEXT NOT NULL,
    sql_query TEXT NOT NULL,
    embedding vector(384),
    roles VARCHAR[] DEFAULT '{}', -- {'cache', 'example', 'golden'}
    status VARCHAR(20) DEFAULT 'unverified', -- 'verified', 'autogenerated', 'tombstoned'
    metadata JSONB DEFAULT '{}',
    performance JSONB DEFAULT '{}', -- { 'execution_time_ms': 120, 'row_count': 50 }
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (signature_key, tenant_id)
);

-- Index for vector similarity search (Tier 2 Lookup)
CREATE INDEX IF NOT EXISTS idx_query_pairs_embedding
ON public.query_pairs
USING hnsw (embedding vector_cosine_ops);

-- Index for role-based retrieval (e.g., fetch all 'example' roles)
CREATE INDEX IF NOT EXISTS idx_query_pairs_roles ON public.query_pairs USING GIN (roles);

-- Index for status filtering
CREATE INDEX IF NOT EXISTS idx_query_pairs_status ON public.query_pairs (status);

-- Composite index for tenant-scoped lookups
CREATE INDEX IF NOT EXISTS idx_query_pairs_tenant ON public.query_pairs (tenant_id);

-- Add comments for documentation
COMMENT ON TABLE public.query_pairs IS 'Unified registry for NLQ-SQL pairs across cache, examples, and evaluation datasets.';
COMMENT ON COLUMN public.query_pairs.signature_key IS 'SHA256 hash of the SpaCy canonical fingerprint.';
COMMENT ON COLUMN public.query_pairs.roles IS 'Usage roles: cache (runtime), example (few-shot), golden (test suite).';
COMMENT ON COLUMN public.query_pairs.status IS 'Trust level: verified (human-in-loop), autogenerated (machine), tombstoned (invalid).';
