import logging
import os
from dataclasses import dataclass
from typing import List

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class RecommendationConfig:
    """Configuration for RecommendationService."""

    limit_default: int
    candidate_multiplier: int
    fallback_enabled: bool
    fallback_threshold: float
    status_priority: List[str]
    exclude_tombstoned: bool
    stale_max_age_days: float
    # RECO_DIVERSITY_ENABLED: Toggle for source-based selection mixing (Default: False)
    diversity_enabled: bool
    # RECO_DIVERSITY_MAX_PER_SOURCE: Cap for examples from ONE source bucket (Default: -1)
    diversity_max_per_source: int
    # RECO_DIVERSITY_MIN_VERIFIED: Minimum floor for approved examples (Default: 0)
    diversity_min_verified: int


def load_recommendation_config() -> RecommendationConfig:
    """Load configuration from environment variables with safe defaults.

    Reads once and returns a RecommendationConfig object.
    Invalid values trigger warnings and fallback to defaults.
    """
    # Defaults (must match legacy hardcoded behavior)
    DEFAULT_LIMIT = 3
    DEFAULT_MULTIPLIER = 2
    DEFAULT_FALLBACK_ENABLED = True
    DEFAULT_FALLBACK_THRESHOLD = 0.85
    DEFAULT_STATUS_PRIORITY = ["verified", "seeded", "autogenerated", "unverified"]

    # 1. Limit Default
    try:
        limit_default = int(os.environ.get("RECO_LIMIT_DEFAULT", DEFAULT_LIMIT))
        if limit_default < 1:
            logger.warning(f"Invalid RECO_LIMIT_DEFAULT {limit_default}, using {DEFAULT_LIMIT}")
            limit_default = DEFAULT_LIMIT
    except ValueError:
        logger.warning(f"Invalid RECO_LIMIT_DEFAULT format, using {DEFAULT_LIMIT}")
        limit_default = DEFAULT_LIMIT

    # 2. Candidate Multiplier
    try:
        candidate_multiplier = int(os.environ.get("RECO_CANDIDATE_MULTIPLIER", DEFAULT_MULTIPLIER))
        if candidate_multiplier < 1:
            logger.warning(
                f"Invalid RECO_CANDIDATE_MULTIPLIER {candidate_multiplier}, "
                f"using {DEFAULT_MULTIPLIER}"
            )
            candidate_multiplier = DEFAULT_MULTIPLIER
    except ValueError:
        logger.warning(f"Invalid RECO_CANDIDATE_MULTIPLIER format, using {DEFAULT_MULTIPLIER}")
        candidate_multiplier = DEFAULT_MULTIPLIER

    # 3. Fallback Enabled
    fallback_val = os.environ.get("RECO_FALLBACK_ENABLED", str(DEFAULT_FALLBACK_ENABLED))
    fallback_enabled = fallback_val.lower() in ("true", "1", "yes", "on")

    # 4. Fallback Threshold
    try:
        fallback_threshold = float(
            os.environ.get("RECO_FALLBACK_THRESHOLD", DEFAULT_FALLBACK_THRESHOLD)
        )
        if not (0.0 <= fallback_threshold <= 1.0):
            logger.warning(
                f"Invalid RECO_FALLBACK_THRESHOLD {fallback_threshold}, "
                f"using {DEFAULT_FALLBACK_THRESHOLD}"
            )
            fallback_threshold = DEFAULT_FALLBACK_THRESHOLD
    except ValueError:
        logger.warning(
            f"Invalid RECO_FALLBACK_THRESHOLD format, using {DEFAULT_FALLBACK_THRESHOLD}"
        )
        fallback_threshold = DEFAULT_FALLBACK_THRESHOLD

    # 5. Status Priority
    status_str = os.environ.get("RECO_STATUS_PRIORITY")
    if status_str:
        status_priority = [s.strip().lower() for s in status_str.split(",") if s.strip()]
        if not status_priority:
            # Case where split resulted in empty
            status_priority = DEFAULT_STATUS_PRIORITY
    else:
        status_priority = DEFAULT_STATUS_PRIORITY

    # 6. Exclude Tombstoned
    # Default is true
    exclude_tombstoned_val = os.environ.get("RECO_EXCLUDE_TOMBSTONED", "true")
    exclude_tombstoned = exclude_tombstoned_val.lower() in ("true", "1", "yes", "on")

    # 7. Stale Max Age Days
    # Default is 0 (disabled)
    try:
        stale_max_age_days = float(os.environ.get("RECO_STALE_MAX_AGE_DAYS", "0"))
    except ValueError:
        logger.warning("Invalid RECO_STALE_MAX_AGE_DAYS format, using 0 (disabled)")
        stale_max_age_days = 0.0

    # 8. Diversity Configuration
    # RECO_DIVERSITY_ENABLED: Toggle for source-based selection mixing (Default: False)
    DEFAULT_DIVERSITY_ENABLED = False
    diversity_enabled_val = os.environ.get("RECO_DIVERSITY_ENABLED", str(DEFAULT_DIVERSITY_ENABLED))
    diversity_enabled = diversity_enabled_val.lower() in ("true", "1", "yes", "on")

    # RECO_DIVERSITY_MAX_PER_SOURCE: Cap for examples from ONE source bucket (Default: -1)
    DEFAULT_MAX_PER_SOURCE = -1
    try:
        diversity_max_per_source = int(
            os.environ.get("RECO_DIVERSITY_MAX_PER_SOURCE", DEFAULT_MAX_PER_SOURCE)
        )
    except ValueError:
        logger.warning(f"Invalid RECO_DIVERSITY_MAX_PER_SOURCE, using {DEFAULT_MAX_PER_SOURCE}")
        diversity_max_per_source = DEFAULT_MAX_PER_SOURCE

    # RECO_DIVERSITY_MIN_VERIFIED: Guaranteed minimum floor for 'approved' examples (Default: 0)
    DEFAULT_MIN_VERIFIED = 0
    try:
        diversity_min_verified = int(
            os.environ.get("RECO_DIVERSITY_MIN_VERIFIED", DEFAULT_MIN_VERIFIED)
        )
    except ValueError:
        logger.warning(f"Invalid RECO_DIVERSITY_MIN_VERIFIED, using {DEFAULT_MIN_VERIFIED}")
        diversity_min_verified = DEFAULT_MIN_VERIFIED

    return RecommendationConfig(
        limit_default=limit_default,
        candidate_multiplier=candidate_multiplier,
        fallback_enabled=fallback_enabled,
        fallback_threshold=fallback_threshold,
        status_priority=status_priority,
        exclude_tombstoned=exclude_tombstoned,
        stale_max_age_days=stale_max_age_days,
        diversity_enabled=diversity_enabled,
        diversity_max_per_source=diversity_max_per_source,
        diversity_min_verified=diversity_min_verified,
    )


# Cached configuration instance
RECO_CONFIG = load_recommendation_config()
