import logging
from dataclasses import dataclass
from typing import List, Optional

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class RecommendationConfig:
    """Configuration for RecommendationService."""

    limit_default: int
    candidate_multiplier: int
    fallback_enabled: bool
    fallback_threshold: float
    status_priority: List[str]
    exclude_tombstoned: bool
    stale_max_age_days: float
    # RECO_DIVERSITY_ENABLED: Toggle for source-based selection mixing (Default: False)
    diversity_enabled: bool
    # RECO_DIVERSITY_MAX_PER_SOURCE: Cap for examples from ONE source bucket (Default: -1)
    diversity_max_per_source: int
    # RECO_DIVERSITY_MIN_VERIFIED: Minimum floor for approved examples (Default: 0)
    diversity_min_verified: int
    # Safety Configuration
    safety_enabled: bool = False
    safety_max_pattern_length: int = 100
    safety_blocklist_regex: Optional[str] = None
    safety_require_sanitizable: bool = True


def load_recommendation_config() -> RecommendationConfig:
    """Load configuration from environment variables with safe defaults.

    Reads once and returns a RecommendationConfig object.
    Invalid values trigger warnings and fallback to defaults.
    """
    from common.config.env import (
        get_env_bool,
        get_env_float,
        get_env_int,
        get_env_list,
        get_env_str,
    )

    # Defaults (must match legacy hardcoded behavior)
    DEFAULT_LIMIT = 3
    DEFAULT_MULTIPLIER = 2
    DEFAULT_FALLBACK_ENABLED = True
    DEFAULT_FALLBACK_THRESHOLD = 0.85
    DEFAULT_STATUS_PRIORITY = ["verified", "seeded", "autogenerated", "unverified"]

    # 1. Limit Default
    try:
        limit_default = get_env_int("RECO_LIMIT_DEFAULT", DEFAULT_LIMIT)
        if limit_default < 1:
            logger.warning(f"Invalid RECO_LIMIT_DEFAULT {limit_default}, using {DEFAULT_LIMIT}")
            limit_default = DEFAULT_LIMIT
    except ValueError:
        logger.warning(f"Invalid RECO_LIMIT_DEFAULT format, using {DEFAULT_LIMIT}")
        limit_default = DEFAULT_LIMIT

    # 2. Candidate Multiplier
    try:
        candidate_multiplier = get_env_int("RECO_CANDIDATE_MULTIPLIER", DEFAULT_MULTIPLIER)
        if candidate_multiplier < 1:
            logger.warning(
                f"Invalid RECO_CANDIDATE_MULTIPLIER {candidate_multiplier}, "
                f"using {DEFAULT_MULTIPLIER}"
            )
            candidate_multiplier = DEFAULT_MULTIPLIER
    except ValueError:
        logger.warning(f"Invalid RECO_CANDIDATE_MULTIPLIER format, using {DEFAULT_MULTIPLIER}")
        candidate_multiplier = DEFAULT_MULTIPLIER

    # 3. Fallback Enabled
    fallback_enabled = get_env_bool("RECO_FALLBACK_ENABLED", DEFAULT_FALLBACK_ENABLED)

    # 4. Fallback Threshold
    try:
        fallback_threshold = get_env_float("RECO_FALLBACK_THRESHOLD", DEFAULT_FALLBACK_THRESHOLD)
        if not (0.0 <= fallback_threshold <= 1.0):
            logger.warning(
                f"Invalid RECO_FALLBACK_THRESHOLD {fallback_threshold}, "
                f"using {DEFAULT_FALLBACK_THRESHOLD}"
            )
            fallback_threshold = DEFAULT_FALLBACK_THRESHOLD
    except ValueError:
        logger.warning(
            f"Invalid RECO_FALLBACK_THRESHOLD format, using {DEFAULT_FALLBACK_THRESHOLD}"
        )
        fallback_threshold = DEFAULT_FALLBACK_THRESHOLD

    # 5. Status Priority
    status_priority = get_env_list("RECO_STATUS_PRIORITY", DEFAULT_STATUS_PRIORITY)
    # Ensure they are lowercased to match original behavior
    status_priority = [s.lower() for s in status_priority]

    # 6. Exclude Tombstoned
    exclude_tombstoned = get_env_bool("RECO_EXCLUDE_TOMBSTONED", True)

    # 7. Stale Max Age Days
    try:
        stale_max_age_days = get_env_float("RECO_STALE_MAX_AGE_DAYS", 0.0)
    except ValueError:
        logger.warning("Invalid RECO_STALE_MAX_AGE_DAYS format, using 0 (disabled)")
        stale_max_age_days = 0.0

    # 8. Diversity Configuration
    diversity_enabled = get_env_bool("RECO_DIVERSITY_ENABLED", False)

    DEFAULT_MAX_PER_SOURCE = -1
    try:
        diversity_max_per_source = get_env_int(
            "RECO_DIVERSITY_MAX_PER_SOURCE", DEFAULT_MAX_PER_SOURCE
        )
    except ValueError:
        logger.warning(f"Invalid RECO_DIVERSITY_MAX_PER_SOURCE, using {DEFAULT_MAX_PER_SOURCE}")
        diversity_max_per_source = DEFAULT_MAX_PER_SOURCE

    DEFAULT_MIN_VERIFIED = 0
    try:
        diversity_min_verified = get_env_int("RECO_DIVERSITY_MIN_VERIFIED", DEFAULT_MIN_VERIFIED)
    except ValueError:
        logger.warning(f"Invalid RECO_DIVERSITY_MIN_VERIFIED, using {DEFAULT_MIN_VERIFIED}")
        diversity_min_verified = DEFAULT_MIN_VERIFIED

    # 9. Safety Configuration
    safety_enabled = get_env_bool("RECO_SAFETY_ENABLED", False)

    DEFAULT_MAX_PATTERN_LEN = 100
    try:
        safety_max_pattern_length = get_env_int(
            "RECO_SAFETY_MAX_PATTERN_LENGTH", DEFAULT_MAX_PATTERN_LEN
        )
        if safety_max_pattern_length < 1:
            logger.warning(
                f"Invalid RECO_SAFETY_MAX_PATTERN_LENGTH {safety_max_pattern_length}, "
                f"using {DEFAULT_MAX_PATTERN_LEN}"
            )
            safety_max_pattern_length = DEFAULT_MAX_PATTERN_LEN
    except ValueError:
        logger.warning(
            f"Invalid RECO_SAFETY_MAX_PATTERN_LENGTH format, using {DEFAULT_MAX_PATTERN_LEN}"
        )
        safety_max_pattern_length = DEFAULT_MAX_PATTERN_LEN

    safety_blocklist_regex = get_env_str("RECO_SAFETY_BLOCKLIST_REGEX")

    safety_require_sanitizable = get_env_bool("RECO_SAFETY_REQUIRE_SANITIZABLE", True)

    return RecommendationConfig(
        limit_default=limit_default,
        candidate_multiplier=candidate_multiplier,
        fallback_enabled=fallback_enabled,
        fallback_threshold=fallback_threshold,
        status_priority=status_priority,
        exclude_tombstoned=exclude_tombstoned,
        stale_max_age_days=stale_max_age_days,
        diversity_enabled=diversity_enabled,
        diversity_max_per_source=diversity_max_per_source,
        diversity_min_verified=diversity_min_verified,
        safety_enabled=safety_enabled,
        safety_max_pattern_length=safety_max_pattern_length,
        safety_blocklist_regex=safety_blocklist_regex,
        safety_require_sanitizable=safety_require_sanitizable,
    )


# Cached configuration instance
RECO_CONFIG = load_recommendation_config()
